config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  root 'static_pages#home'
  get 'sessions/new'
  get    '/signup', to: 'parents#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  get '/new_child', to: 'children#new'
  post '/new_child', to: 'children#new'
  get '/child_search', to: 'child#search'

  resources :parents 
  resources :children
   
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update, :destroy]

  # GET /children
  # GET /children.json
  def index
    @children = Child.all
  end

  # GET /children/1
  # GET /children/1.json
  def show
    @child = Child.find(params[:id])
    @wishlist = Wishlist.where(child_id: @child.id)
    session[:current_child_id] = @child.id
  end

  # GET /children/new
  def new
    @child = Child.new
  end

  # GET /children/1/edit
  def edit
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        
        format.html { redirect_to @child }
        format.json { render :show, status: :created, location: @child }
      else
        format.html { render :new }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1
  # PATCH/PUT /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to @child, notice: 'Child was successfully updated.' }
        format.json { render :show, status: :ok, location: @child }
      else
        format.html { render :edit }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child.destroy
    respond_to do |format|
      format.html { redirect_to children_url, notice: 'Child was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    name = params[search] + '%'
    id = session[:current_child_id]
    @wishlist= Wishlist.where(['name LIKE ? AND child_id = ?', name, id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_params
      params.require(:child).permit(:name, :parent_id)
    end
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/_form.html.erb
<%= form_with(model: child, local: true) do |form| %>
  <% if child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% child.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.number_field :parent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/children/_results.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Your Present</th>
      
      <th>Change Mind?</th>
      
  </thead>
  <tbody>
    <% @wishlist.each do |w| %>
      <tr>
        <td><%= w.name %></td>
        
        <td><%= link_to "delete", w, :method => :delete,
                        :remote => true, :class => 'delete_wishlist',class: "tdlink2" %>
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/children/_wishlist.html.erb
<tr>
  <td><%= w.name %></td>
  
  <td><%= link_to "delete", w, :method => :delete,
                  :remote => true, :class => 'delete_wishlist' %></td>
</tr>

app/views/children/child_search.js.erb
$('.delete_wishlist').bind('ajax:success',function() {
  $(this).closest('tr').fadeOut();
});

$("#results").html(
  "<%= escape_javascript(render("results")) %>");

app/views/children/edit.html.erb
<h1>Editing Child</h1>

<%= render 'form', child: @child %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Children</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.name %></td>
        <td><%= child.parent_id %></td>
        <td><%= link_to 'Show', child %></td>
        <td><%= link_to 'Edit', edit_child_path(child) %></td>
        <td><%= link_to 'Destroy', child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Child', new_child_path %>

app/views/children/new.html.erb
<body class="adults">
  <h1>Add your Child</h1>
  <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@child) do |f| %>
        <%= f.label :name, "Child's Name" %>
        <%= f.text_field :name %>
  
        <%= f.hidden_field :parent_id, value: session[:parent_id] %>
  
        <%= f.submit "Create Your Child's Page", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
  <%= debug(params) if Rails.env.development? %>
</body>

app/views/children/show.html.erb
<body class="kids">
<div class="winter-is-coming">
  
  <div class="snow snow--near"></div>
  <div class="snow snow--near snow--alt"></div>
  
  <div class="snow snow--mid"></div>
  <div class="snow snow--mid snow--alt"></div>
  
  <div class="snow snow--far"></div>
  <div class="snow snow--far snow--alt"></div>
</div>  
      <%= render 'layouts/header' %>
          <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <h1 class="kidshow"><i class="fas fa-tree"></i> Happy Holidays <%= @child.name %> <i class="fas fa-tree"></i></h1>

      
        <div class="row">
          <div class="col-md-6 col-md-offset-6">
            
            <h2 class= "kidsh2">Click the button to start adding presents to your list!</h2>
            <div class="move">
            <%= link_to "Add Present", new_wishlist_path, class: "btn btn-lg btn-success" %>
            </div> 
            <%= render 'results' %>
         
         
          </div>
        
         
        
        
        </div>
      
        <%#= debug(params) if Rails.env.development? %>
    
</body>