config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  root 'static_pages#home'
  get 'sessions/new'
  get    '/signup', to: 'parents#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  get '/new_child', to: 'children#new'
  post '/new_child', to: 'children#new'
  get '/child_search', to: 'child#search'

  resources :parents 
  resources :children
   
end

app/models/parent.rb
class Parent < ApplicationRecord
  before_save { self.name = self.name.downcase }
  has_many :children
  validates :name, presence: true, length: { minimum: 8, maximum: 40 },
                   uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8, maximum: 40 }

  #has_secure_password
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
    @parent = Parent.find(params[:id])
    @child = Child.where(parent_id: @parent.id)
    session[:parent_id] = @parent.id
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        log_in @parent
        #welcome flash can go here
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
        #redirect_to @parent
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:name, :password)
    end
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/_form.html.erb
<%= form_with(model: parent, local: true) do |form| %>
  <% if parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= parent.password %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<body>
    <h1>Register</h1>
    
    <%= render 'layouts/header' %>
        <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@parent) do |f| %>
          <%= render 'shared/error_messages' %>
    
          <%= f.label :name, "Username" %>
          <%= f.text_field :name %>
    
          <%= f.label :password %>
          <%= f.password_field :password %>
          
          <%= f.label :password_confirmation, "Confirm Password" %>
          <%= f.password_field :password_confirmation %>
    
          <%= f.submit "Create Account", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
    <%= debug(params) if Rails.env.development? %>
</body> 

app/views/parents/show.html.erb
    
    
<body class= "adults">   
    <h1 class="parshow">Welcome <%= @parent.name%></h1>
    
    
    <%= render 'layouts/header' %>
        <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="col-md-6 col-md-offset-3">
      <table class="table">
        <thead>
          <tr>
            <th>Your Children</th>
          </tr>
        </thead>
        <tbody>
          <% @child.each do |i| %>
            <tr>
              <td><%= link_to i.name, i, class: "tdlink" %>
                <i class="fas fa-child"></i></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <p class="show">Have More Children? <%= link_to "Add New Child ", new_child_path, class: "btn btn-success" %></p>
    </div>
    <%#= debug(params) if Rails.env.development? %>
</body>    