config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  root 'static_pages#home'
  get 'sessions/new'
  get    '/signup', to: 'parents#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  get '/new_child', to: 'children#new'
  post '/new_child', to: 'children#new'
  get '/child_search', to: 'child#search'

  resources :parents 
  resources :children
   
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :child
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  
  # initialize default value
  after_initialize :init
  def init
    self.buy = false if self.buy.nil?
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  # GET /wishlists/new
  def new
    @wishlist = Wishlist.new
  end

  # GET /wishlists/1/edit
  def edit
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @wishlist = Wishlist.new(wishlist_params)

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to "/children/#{session[:current_child_id]}" }
        #format.html { redirect_to children_path(id: 
        #format.html { redirect_to @wishlist, notice: 'Wishlist was successfully created.' }
        #format.json { render :show, status: :created, location: @wishlist }
      else
        format.html { render :new }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlist }
      else
        format.html { render :edit }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist.destroy
    respond_to do |format|
      #format.html { redirect_to "/children/#{session[:current_child_id]}" }
      #format.html { redirect_to wishlists_url, notice: 'Wishlist was successfully destroyed.' }
      format.html { redirect_to request.referrer || root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_params
      params.require(:wishlist).permit(:name, :child_id, :buy)
    end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= form_with(model: wishlist, local: true) do |form| %>
  <% if wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% wishlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :child_id %>
    <%= form.number_field :child_id %>
  </div>

  <div class="field">
    <%= form.label :buy %>
    <%= form.check_box :buy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wishlists</h1>

<table>
  <thead>
    <tr>
      <th>Present</th>
      <th>Child</th>
      <th>Buy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      <tr>
        <td><%= wishlist.name %></td>
        <td><%= wishlist.child_id %></td>
        <td><%= wishlist.buy %></td>
        <td><%= link_to 'Show', wishlist %></td>
        <td><%= link_to 'Edit', edit_wishlist_path(wishlist) %></td>
        <td><%= link_to 'Destroy', wishlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wishlist', new_wishlist_path %>

app/views/wishlists/new.html.erb
<body class="gifts">
  <div class="winter-is-coming">
    
    <div class="snow snow--near"></div>
    <div class="snow snow--near snow--alt"></div>
    
    <div class="snow snow--mid"></div>
    <div class="snow snow--mid snow--alt"></div>
    
    <div class="snow snow--far"></div>
    <div class="snow snow--far snow--alt"></div>
  </div>
  <%= render 'layouts/header' %>
  
  
  <h1 class="kidshow2"><i class="fas fa-gift"></i> Write your Present <i class="fas fa-gift"></i></h1>
  <h2 class="kidsh2">Add what present you want Santa to bring!</h2>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@wishlist) do |f| %>
        <%= f.label :name, "Present Name" %>
        <%= f.text_field :name %>
        
  
        <%= f.hidden_field :child_id, value: session[:current_child_id] %>
        <div class="kidfont">
        <%= f.submit "Add it to your Wishlist", class: "btn btn-lg btn-success" %>
        </div>
      <% end %>
  
    </div>
  </div>
</body>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Present:</strong>
  <%= @wishlist.name %>
</p>

<p>
  <strong>Child:</strong>
  <%= @wishlist.child_id %>
</p>

<p>
  <strong>Buy:</strong>
  <%= @wishlist.buy %>
</p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>