config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  root 'static_pages#home'
  get 'sessions/new'
  get    '/signup', to: 'parents#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  get '/new_child', to: 'children#new'
  post '/new_child', to: 'children#new'
  get '/child_search', to: 'child#search'

  resources :parents 
  resources :children
   
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Santa Wishes",root_path, id: "logo" %>
        
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if logged_in? %>
              
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_parent %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign Out",logout_path,method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign In", login_path %></li>
            <% end %>
          </ul>  
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Schoolbell" rel="stylesheet">
    <title>Santa Wishes - Make your Wish List to Santa</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <%= yield %>
</html>